### ISSUE TITLE
Feel free to use any of this code...

### ISSUE THREAD

**Issue by biobrad** [beardymcjohnface/Koverage#1]
Hi Michael,

How are you?

I saw you were working on a coverage stats pipeline and thought you may be able to re-use some of the work i have already done in this space.

I use shell scripting to get the basics and then i have a second script which uses datapane and plotly to create a nice visualisation. (through the creation of this visualisation it made me realise just how important it is to trash the shorter contigs after assembly)

https://github.com/biobrad/ContigQuality

Feel free to re-use anything that you might find useful.

cheers mate
Brad

![image](https://user-images.githubusercontent.com/55652506/235328593-81992735-255e-4c32-8bed-db1413400853.png)

**Comment by beardymcjohnface** [comment]
Hi Brad,
Thanks for reaching out; I'll have a look. I do like your visualisation.
The idea behind the pipeline is that we've been using other packages that calculate coverage metrics, which work fine but are a bit slow when dealing with lots of samples because they're hammering the HDDs. We're writing this to reduce the IO burden as much as possible as it's a big bottleneck in some of our pipelines. I'm aiming for a single read operation of the reads files and a single (optional) write of the bam files, plus the summary files which are small.
Let me know if you'd like to be a contributor and I'll open a slack channel or something. I'm hoping to publish this in JOSS once it's up and running and we've added unit tests and CI.
All the best,
Mike

**Comment by biobrad** [comment]
Hey Mike,
I will close this off, i created a slack channel. :-)
cheers
Brad
